Repository wethegit/component-library, pull requests merged in 2024-05, with the labels that each got.

#187 [COMP] BackToTop: various fixes, per project implementation
  packages/wethegit-components/src/components/back-to-top/back-to-top.module.scss
  packages/wethegit-components/src/components/back-to-top/back-to-top.tsx
Labels: bug, COMP

#182 release v3.0.6
  .changeset/six-zoos-check.md
  packages/tsconfig/react-library.json
  packages/wethegit-components-cli/src/registry-index.ts
  packages/wethegit-components/src/components/back-to-top/back-to-top.module.scss
  packages/wethegit-components/src/components/back-to-top/back-to-top.tsx
  packages/wethegit-components/src/components/breakpoint-snipe/breakpoint-snipe.module.scss
  packages/wethegit-components/src/components/breakpoint-snipe/breakpoint-snipe.tsx
  packages/wethegit-components/src/components/flex/flex.module.scss
  packages/wethegit-components/src/components/flex/flex.tsx
  packages/wethegit-components/src/components/grid-layout/column/column.module.scss
  packages/wethegit-components/src/components/text/styles/_text-utilities.scss
  packages/wethegit-components/src/components/text/styles/text-utilities.stories.mdx
  packages/wethegit-components/src/components/text/styles/text.scss
  packages/wethegit-components/src/components/text/styles/text.stories.mdx
  packages/wethegit-components/src/components/text/text.module.scss
  packages/wethegit-components/src/components/text/text.tsx
  packages/wethegit-components/src/hooks/index.ts
  packages/wethegit-components/src/hooks/use-breakpoints/index.ts
  packages/wethegit-components/src/hooks/use-breakpoints/readme.stories.mdx
  packages/wethegit-components/src/hooks/use-breakpoints/use-breakpoints.module.scss
  packages/wethegit-components/src/hooks/use-breakpoints/use-breakpoints.ts
  packages/wethegit-components/src/styles/reset.scss
  packages/wethegit-components/src/utilities/build-breakpoint-classnames/build-breakpoint-classnames.stories.mdx
  packages/wethegit-components/src/utilities/build-breakpoint-classnames/build-breakpoint-classnames.ts
  packages/wethegit-components/src/utilities/color/color.ts
  packages/wethegit-components/src/utilities/spacing/spacing.ts
  yarn.lock
Labels: DOCS, COMP

#204 feature: storybook v8
  .changeset/cold-squids-work.md
  .github/dependabot.yml
  package.json
  packages/wethegit-components-cli/src/commands/add/utils/copy-registry-items.ts
  packages/wethegit-components-cli/src/commands/init/utils/copy-global-styles.ts
  packages/wethegit-components/.storybook/main.ts
  packages/wethegit-components/.storybook/preview.ts
  packages/wethegit-components/package.json
  packages/wethegit-components/src/components/back-to-top/back-to-top.stories.tsx
  packages/wethegit-components/src/components/back-to-top/readme.mdx
  packages/wethegit-components/src/components/breakpoint-snipe/readme.mdx
  packages/wethegit-components/src/components/grid-layout/readme.mdx
  packages/wethegit-components/src/components/grid-layout/styles/grid-layout-utilities.mdx
  packages/wethegit-components/src/components/grid-layout/styles/grid-layout.mdx
  packages/wethegit-components/src/components/icon/readme.mdx
  packages/wethegit-components/src/components/image-group/readme.mdx
  packages/wethegit-components/src/components/in-view/docs-animation-presets.mdx
  packages/wethegit-components/src/components/in-view/readme.mdx
  packages/wethegit-components/src/components/modal/modal.stories.tsx
  packages/wethegit-components/src/components/modal/readme.mdx
  packages/wethegit-components/src/components/navigation/readme.mdx
  packages/wethegit-components/src/components/text/readme.mdx
  packages/wethegit-components/src/components/text/styles/text-utilities.mdx
  packages/wethegit-components/src/components/text/styles/text.mdx
  packages/wethegit-components/src/components/visually-hidden-links/readme.mdx
  packages/wethegit-components/src/components/visually-hidden/readme.mdx
  packages/wethegit-components/src/hooks/use-breakpoints/readme.mdx
  packages/wethegit-components/src/hooks/use-breakpoints/readme.stories.mdx
  packages/wethegit-components/src/index.mdx
  packages/wethegit-components/src/styles/accessibility/accessibility-utilities.mdx
  packages/wethegit-components/src/styles/animation/animation-utilities.mdx
  packages/wethegit-components/src/styles/animation/animation.mdx
  packages/wethegit-components/src/styles/breakpoints/breakpoints-variables.mdx
  packages/wethegit-components/src/styles/global.mdx
  packages/wethegit-components/src/styles/math/math-utilities.mdx
  packages/wethegit-components/src/styles/reset.mdx
  packages/wethegit-components/src/utilities/build-breakpoint-classnames/build-breakpoint-classnames.mdx
  packages/wethegit-components/src/utilities/classnames/classnames.mdx
  packages/wethegit-components/src/utilities/color/color.mdx
  packages/wethegit-components/src/utilities/color/styles/color-utilities.mdx
  packages/wethegit-components/src/utilities/color/styles/color-variables.mdx
  packages/wethegit-components/src/utilities/spacing/spacing.mdx
  packages/wethegit-components/src/utilities/spacing/styles/spacing-utilities.mdx
  packages/wethegit-components/src/utilities/spacing/styles/spacing-variables.mdx
  packages/wethegit-components/src/utilities/visibility/visibility.mdx
  yarn.lock
Labels: dependencies

#168 (component) fix: updates InView with latest hook
  .changeset/friendly-radios-sleep.md
  packages/wethegit-components/package.json
  packages/wethegit-components/src/components/in-view/components/in-view-item/in-view-item.tsx
  packages/wethegit-components/src/components/in-view/in-view.stories.tsx
  packages/wethegit-components/src/components/in-view/in-view.tsx
  packages/wethegit-components/src/components/in-view/index.tsx
  packages/wethegit-components/src/components/in-view/preset-examples.stories.tsx
  packages/wethegit-components/src/components/in-view/readme.mdx
  packages/wethegit-components/types/wethegit-react-hooks.d.ts
  yarn.lock
Labels: bug

#242 feature(components): adds `IntRange` type
  .changeset/happy-kings-bathe.md
  package.json
  packages/wethegit-components/.storybook/main.ts
  packages/wethegit-components/package.json
  packages/wethegit-components/src/types/utils.d.ts
  packages/wethegit-components/src/utilities/spacing/spacing.ts
  yarn.lock
Labels: enhancement, COMP

#243 fix(components): adds `use client`
  .changeset/shaggy-geckos-tan.md
  packages/wethegit-components/src/components/back-to-top/back-to-top.tsx
  packages/wethegit-components/src/components/breakpoint-snipe/breakpoint-snipe.tsx
  packages/wethegit-components/src/components/in-view/components/in-view-item/in-view-item.tsx
Labels: enhancement

#245 fix: update GH action node to use `.nvmrc`
  .github/pull_request_template.md
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/storybook-tests.yml
  .github/workflows/storybook.yml
Labels: enhancement
